name: artigianofast github workflow 

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}          
        key: ${{ secrets.SSH_KEY }}
        script: |
            sudo -s
            cd /home/ubuntu/artigianofast
            git pull origin main
            sudo docker compose up -d 
            echo "Deployed successfully"
            pm2 restart all
            echo "PM2 restarted successfully"
            sudo systemctl restart nginx 
            echo "Nginx restarted successfully"
            exit 0
            